Feature/inventory bar widget
BattleQuiche/Frontend pull request #35
Opened 2021-06-02 16:21 UTC by Laroche-Nicolas

2021-06-02 16:23 UTC, zaktolba approved these changes

2021-06-04 19:01 UTC, MaxenceMottard requested changes

2021-06-04 19:01 UTC, MaxenceMottard commented on src/reusables/InventoryBarWidget.vue
> +      console.log(`l'id de l'objet est ${item.id}`)
Could you emit an event with this.$emit() function.
Documentation: https://fr.vuejs.org/v2/guide/components-custom-events.html#Noms-d’evenements

2021-06-04 20:37 UTC, MaxenceMottard requested changes

2021-06-04 20:37 UTC, MaxenceMottard commented on src/reusables/InventoryBarWidget.vue
> +  border: 1px black solid;
needs to use `position: fixed` css property and place the element at the bottom of the screen and centered horizontally

2021-06-04 20:40 UTC, MaxenceMottard commented
When your bar is in the fixed position, you can call your component in the Party.vue file before the component with the ID `#debug-button`.

2021-06-04 20:50 UTC, MaxenceMottard commented
Please fix bar max-width

2021-06-08 19:12 UTC, MaxenceMottard approved these changes

2021-06-08 19:13 UTC, merged